<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="IdentityModel" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreWebApiBoilerPlate.Common\CoreWebApiBoilerPlate.Common.csproj" />
    <ProjectReference Include="..\CoreWebApiBoilerPlate.DAL\CoreWebApiBoilerPlate.DAL.csproj" />
    <ProjectReference Include="..\CoreWebApiBoilerPlate.Domain\CoreWebApiBoilerPlate.Domain.csproj" />
  </ItemGroup>

</Project>
